name: studymate_ai_app
description: "StudyMate AI - Your AI-powered study companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_riverpod: ^2.5.0
  
  firebase_core: ^2.5.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  
  dio: ^5.4.0
  
  go_router: ^14.0.0
  
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  dartz: ^0.10.1
  
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter
  
  mocktail: ^1.0.2

  flutter_lints: ^5.0.0
  
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
