name: studymate_ai_app
description: "StudyMate AI - Your AI-powered study companion"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_riverpod: ^2.6.1
  
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  
  dio: ^5.9.0
  
  go_router: ^14.0.0
  
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  dartz: ^0.10.1
  
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3 
  shared_preferences: ^2.5.3
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter
  
  mocktail: ^1.0.2

  flutter_lints: ^5.0.0
  
  build_runner: ^2.7.0
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.11.0

flutter:
  uses-material-design: true
